
package co.edu.unicauca.mvc.vistas.postular;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import co.edu.unicauca.mvc.modelos.Conferencia;
import co.edu.unicauca.isii.services.ConferenciaServices;
import co.edu.unicauca.isii.services.ServicesFacade;
import java.util.List;

/**
 *
 * @author thali
 */
public class panelConsultarConferencia extends javax.swing.JFrame {

    
    private ServicesFacade servicesFacade;
  
    public panelConsultarConferencia(ServicesFacade servicesFacade) {
        initComponents();
        this.servicesFacade = servicesFacade;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelConsultarConferencia = new javax.swing.JLabel();
        jLabelConsultarporNombre = new javax.swing.JLabel();
        jLabelConsultarporFecha = new javax.swing.JLabel();
        jButtonConsultarConferencia = new javax.swing.JButton();
        jTextFieldConsultarporNombre = new javax.swing.JTextField();
        jTextFieldConsultarporFecha = new javax.swing.JTextField();
        jButtonListadoConferencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelConsultarConferencia.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 20)); // NOI18N
        jLabelConsultarConferencia.setForeground(new java.awt.Color(102, 102, 102));
        jLabelConsultarConferencia.setText("Consultar conferencia");

        jLabelConsultarporNombre.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelConsultarporNombre.setForeground(new java.awt.Color(102, 102, 102));
        jLabelConsultarporNombre.setText("Consultar por nombre                     ó");

        jLabelConsultarporFecha.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 16)); // NOI18N
        jLabelConsultarporFecha.setForeground(new java.awt.Color(102, 102, 102));
        jLabelConsultarporFecha.setText("Consultar por fecha");

        jButtonConsultarConferencia.setBackground(new java.awt.Color(145, 173, 180));
        jButtonConsultarConferencia.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jButtonConsultarConferencia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarConferencia.setText("Consultar");
        jButtonConsultarConferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarConferenciaActionPerformed(evt);
            }
        });

        jButtonListadoConferencias.setBackground(new java.awt.Color(145, 173, 180));
        jButtonListadoConferencias.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jButtonListadoConferencias.setForeground(new java.awt.Color(255, 255, 255));
        jButtonListadoConferencias.setText("Listado conferencias");
        jButtonListadoConferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListadoConferenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldConsultarporNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(jTextFieldConsultarporFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabelConsultarConferencia))
                            .addComponent(jLabelConsultarporNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonListadoConferencias)
                            .addComponent(jLabelConsultarporFecha))))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConsultarConferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultarConferencia)
                    .addComponent(jButtonListadoConferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultarporNombre)
                    .addComponent(jLabelConsultarporFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConsultarporNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConsultarporFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButtonConsultarConferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarConferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarConferenciaActionPerformed

       String nombre = jTextFieldConsultarporNombre.getText();
       String fecha = jTextFieldConsultarporFecha.getText();
       
       // Validar que los campos no estén vacíos
        if (nombre.isEmpty() && fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre o una fecha para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (fecha.isEmpty()){
            Conferencia conferenciaEncontrada = servicesFacade.buscarPorNombre(nombre);
            // Mostrar mensaje según el resultado del registro
            if (conferenciaEncontrada != null) {
                JOptionPane.showMessageDialog(this, "Conferencia encontrada", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al consultar la conferencia", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (nombre.isEmpty()){
            Conferencia conferenciaEncontrada = servicesFacade.buscarPorFecha(fecha);
            // Mostrar mensaje según el resultado del registro
            if (conferenciaEncontrada != null) {
                JOptionPane.showMessageDialog(this, "Conferencia encontrada", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error al consultar la conferencia", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
       
    }//GEN-LAST:event_jButtonConsultarConferenciaActionPerformed

    private void jButtonListadoConferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoConferenciasActionPerformed
        panelListarConferencias1 objpanelListarConferencias= 
                new panelListarConferencias1(this.servicesFacade);
        objpanelListarConferencias.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        objpanelListarConferencias.setVisible(true);
    }//GEN-LAST:event_jButtonListadoConferenciasActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarConferencia;
    private javax.swing.JButton jButtonListadoConferencias;
    private javax.swing.JLabel jLabelConsultarConferencia;
    private javax.swing.JLabel jLabelConsultarporFecha;
    private javax.swing.JLabel jLabelConsultarporNombre;
    private javax.swing.JTextField jTextFieldConsultarporFecha;
    private javax.swing.JTextField jTextFieldConsultarporNombre;
    // End of variables declaration//GEN-END:variables
}
