package co.edu.unicauca.mvc.vistas.asignarrevisor;

//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;

import co.edu.unicauca.isii.services.ConferenciaServices;
import co.edu.unicauca.mvc.modelos.Conferencia;
import co.edu.unicauca.mvc.vistas.login.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;

/**
 *
 * @author earea
 */
public class panelSeleccionarConferencia extends javax.swing.JPanel {

    private ConferenciaServices servicioConferencia;
    
    /**
     * Creates new form panelListarConferencias
     */
    public panelSeleccionarConferencia(ConferenciaServices servicioConferencia) {
        initComponents();
        this.servicioConferencia = servicioConferencia;
        iniciarlizarTabla();
        llenarTabla();
    }

    private void iniciarlizarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tema");      
        model.addColumn("Nombre");    
        model.addColumn("Descripción"); 
        this.jTableListadoConferencias.setModel(model);
    }

    private void llenarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.jTableListadoConferencias.getModel();
        limpiarTabla(); // Limpia las filas existentes
        ArrayList<Conferencia> listaConferencias = (ArrayList<Conferencia>) this.servicioConferencia.listarConferencias();

        if (listaConferencias.isEmpty()) {
            // Si no hay conferencias, muestra un mensaje en el JLabel
            textoListado.setText("En este momento no hay conferencias para asignar revisor.");
        } else {
            // Si hay conferencias, actualiza el texto
            textoListado.setText("Haz doble click en la conferencia para asignarle un revisor.");
            for (Conferencia conferencia : listaConferencias) {
                String[] fila = {
                    conferencia.getTema(),      
                    conferencia.getNombre(),      
                    conferencia.getDescripcion()  
                };
                model.addRow(fila);
            }
        }
    }

    public void limpiarTabla(){
        DefaultTableModel modelo=(DefaultTableModel) this.jTableListadoConferencias.getModel();
        int filas=this.jTableListadoConferencias.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioConfes = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoConferencias = new javax.swing.JTable();
        jPanelsuperior = new javax.swing.JPanel();
        jLabelListadoConferencias = new javax.swing.JLabel();
        textoListado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));
        setPreferredSize(new java.awt.Dimension(620, 400));
        setRequestFocusEnabled(false);

        espacioConfes.setBackground(new java.awt.Color(236, 236, 236));

        jPanelCentral.setBackground(new java.awt.Color(236, 236, 236));

        jTableListadoConferencias.setBackground(new java.awt.Color(236, 236, 236));
        jTableListadoConferencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 173, 180)));
        jTableListadoConferencias.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jTableListadoConferencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", ""
            }
        ));
        jScrollPane1.setViewportView(jTableListadoConferencias);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelsuperior.setBackground(new java.awt.Color(236, 236, 236));

        jLabelListadoConferencias.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelListadoConferencias.setForeground(new java.awt.Color(102, 102, 102));
        jLabelListadoConferencias.setText("Listado conferencias");

        textoListado.setText("Haz doble click en la conferencia para asignarle un revisor.");

        javax.swing.GroupLayout jPanelsuperiorLayout = new javax.swing.GroupLayout(jPanelsuperior);
        jPanelsuperior.setLayout(jPanelsuperiorLayout);
        jPanelsuperiorLayout.setHorizontalGroup(
            jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                .addGroup(jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabelListadoConferencias))
                    .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(textoListado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelsuperiorLayout.setVerticalGroup(
            jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelListadoConferencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(textoListado))
        );

        javax.swing.GroupLayout espacioConfesLayout = new javax.swing.GroupLayout(espacioConfes);
        espacioConfes.setLayout(espacioConfesLayout);
        espacioConfesLayout.setHorizontalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelsuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        espacioConfesLayout.setVerticalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelsuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(espacioConfes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioConfes;
    private javax.swing.JLabel jLabelListadoConferencias;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelsuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListadoConferencias;
    private javax.swing.JLabel textoListado;
    // End of variables declaration//GEN-END:variables
}
