package co.edu.unicauca.mvc.vistas.asignarrevisor;

//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;

import co.edu.unicauca.isii.services.ArticuloServices;
import co.edu.unicauca.isii.services.ServicesFacade;
import co.edu.unicauca.mvc.modelos.Articulo;
import co.edu.unicauca.mvc.vistas.GUIOpciones;
import co.edu.unicauca.mvc.vistas.asignarrevisor.panelAsignarRevisor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;

/**
 *
 * @author earea
 */
public class panelSeleccionarArticulo extends javax.swing.JPanel {

    private ServicesFacade servicesFacade;
    
    /**
     * Creates new form panelListarConferencias
     */
    public panelSeleccionarArticulo(ServicesFacade servicesFacade) {
        initComponents();
        this.servicesFacade = servicesFacade;
        iniciarlizarTabla();
        llenarTabla();
    }

    private void iniciarlizarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");      
        model.addColumn("Descripción"); 
        model.addColumn("Resumen"); 
        this.jTableListadoArticulos.setModel(model);
    }

    private void llenarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.jTableListadoArticulos.getModel();
        limpiarTabla(); // Limpia las filas existentes
        ArrayList<Articulo> listaArticulos = (ArrayList<Articulo>) this.servicesFacade.listarArticulos();

        if (listaArticulos.isEmpty()) {
            // Si no hay conferencias, muestra un mensaje en el JLabel
            textoListado.setText("En este momento no hay conferencias para asignar revisor.");
        } else {
            // Si hay conferencias, actualiza el texto
            textoListado.setText("Haz doble click en la conferencia para asignarle un revisor.");
            for (Articulo articulo : listaArticulos) {
                String[] fila = {
                    articulo.getTitulo(),      
                    articulo.getDescripcion(),
                    articulo.getResumen()
                };
                model.addRow(fila);
            }
        }
    }

    public void limpiarTabla(){
        DefaultTableModel modelo=(DefaultTableModel) this.jTableListadoArticulos.getModel();
        int filas=this.jTableListadoArticulos.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
    }

    private void addTableClickListener() {
        jTableListadoArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    // Obtener la fila seleccionada
                    int selectedRow = jTableListadoArticulos.getSelectedRow();
                    if (selectedRow != -1) {
                        // Cambia al panel de asignar revisor sin pasar datos explícitos
                        panelAsignarRevisor panelAsignarRevisor = new panelAsignarRevisor(servicesFacade);
                        GUIOpciones guiOpciones = (GUIOpciones) javax.swing.SwingUtilities.getWindowAncestor(panelSeleccionarArticulo.this);
                        guiOpciones.mostrarPanel(panelAsignarRevisor);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(panelSeleccionarArticulo.this, "Por favor selecciona una fila válida.");
                    }
                }
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioConfes = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoArticulos = new javax.swing.JTable();
        jPanelsuperior = new javax.swing.JPanel();
        jLabelListadoConferencias = new javax.swing.JLabel();
        textoListado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));
        setPreferredSize(new java.awt.Dimension(620, 400));
        setRequestFocusEnabled(false);

        espacioConfes.setBackground(new java.awt.Color(236, 236, 236));

        jPanelCentral.setBackground(new java.awt.Color(236, 236, 236));

        jTableListadoArticulos.setBackground(new java.awt.Color(236, 236, 236));
        jTableListadoArticulos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 173, 180)));
        jTableListadoArticulos.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jTableListadoArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", ""
            }
        ));
        jScrollPane1.setViewportView(jTableListadoArticulos);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1)
                .addGap(58, 58, 58))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jPanelsuperior.setBackground(new java.awt.Color(236, 236, 236));

        jLabelListadoConferencias.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelListadoConferencias.setForeground(new java.awt.Color(102, 102, 102));
        jLabelListadoConferencias.setText("Listado artículos");

        textoListado.setText("Haz doble click en el artículo para asignarle un revisor.");

        javax.swing.GroupLayout jPanelsuperiorLayout = new javax.swing.GroupLayout(jPanelsuperior);
        jPanelsuperior.setLayout(jPanelsuperiorLayout);
        jPanelsuperiorLayout.setHorizontalGroup(
            jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                .addGroup(jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabelListadoConferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(textoListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(183, 183, 183))
        );
        jPanelsuperiorLayout.setVerticalGroup(
            jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelListadoConferencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(textoListado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout espacioConfesLayout = new javax.swing.GroupLayout(espacioConfes);
        espacioConfes.setLayout(espacioConfesLayout);
        espacioConfesLayout.setHorizontalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelsuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        espacioConfesLayout.setVerticalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelsuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioConfes;
    private javax.swing.JLabel jLabelListadoConferencias;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelsuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListadoArticulos;
    private javax.swing.JLabel textoListado;
    // End of variables declaration//GEN-END:variables
}
