package co.edu.unicauca.mvc.vistas.asignarrevisor;

//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;

import co.edu.unicauca.isii.services.ArticuloServices;
import co.edu.unicauca.isii.services.RevisorServices;
import co.edu.unicauca.mvc.modelos.Revisor;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
//import co.edu.unicauca.mvc.controladores.ServicioAlmacenamientoArticulos;

/**
 *
 * @author earea
 */
public class panelAsignarRevisor extends javax.swing.JPanel {

    private RevisorServices servicioRevisor;
    private ArticuloServices servicioArticulo;
    
    /**
     * Creates new form panelAsignarRevisor
     */
    public panelAsignarRevisor(ArticuloServices servicioArticulo) {
        initComponents();
        this.servicioRevisor = servicioRevisor;
        this.servicioArticulo = servicioArticulo;
        iniciarlizarTabla();
        llenarTabla();
    }

    private void iniciarlizarTabla() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nombre");      
        model.addColumn("Titulo Universitario");
        this.jTableListadoRevisores.setModel(model);
    }

    private void llenarTabla() {
        DefaultTableModel model = (DefaultTableModel) this.jTableListadoRevisores.getModel();
        limpiarTabla(); 
        ArrayList<Revisor> listaRevisores = (ArrayList<Revisor>) this.servicioRevisor.listarRevisores();

        if (listaRevisores.isEmpty()) {
            // Si no hay conferencias, muestra un mensaje en el JLabel
            txtCabecera.setText("En este momento no hay revisores.");
        } else {
            // Si hay conferencias, actualiza el texto
            txtCabecera.setText("Haz doble click en la conferencia para asignarle un revisor.");
            for (Revisor revisor : listaRevisores) {
                String[] fila = {    
                    revisor.getNombre(),      
                    revisor.getTituloUniversitario() // Pregunta: título-disponibilidad
                };
                model.addRow(fila);
            }
        }
    }

    public void limpiarTabla(){
        DefaultTableModel modelo=(DefaultTableModel) this.jTableListadoRevisores.getModel();
        int filas=this.jTableListadoRevisores.getRowCount();
        for (int i = 0;filas>i; i++) {
            modelo.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espacioConfes = new javax.swing.JPanel();
        jPanelCentral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoRevisores = new javax.swing.JTable();
        jPanelsuperior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        txtCabecera = new javax.swing.JLabel();

        setBackground(new java.awt.Color(236, 236, 236));
        setPreferredSize(new java.awt.Dimension(620, 400));
        setRequestFocusEnabled(false);

        espacioConfes.setBackground(new java.awt.Color(236, 236, 236));

        jPanelCentral.setBackground(new java.awt.Color(236, 236, 236));

        jTableListadoRevisores.setBackground(new java.awt.Color(236, 236, 236));
        jTableListadoRevisores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 173, 180)));
        jTableListadoRevisores.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jTableListadoRevisores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", ""
            }
        ));
        jScrollPane1.setViewportView(jTableListadoRevisores);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelsuperior.setBackground(new java.awt.Color(236, 236, 236));

        titulo.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(102, 102, 102));
        titulo.setText("Revisores");

        txtCabecera.setText("Haz doble click en la conferencia para asignarle un revisor.");

        javax.swing.GroupLayout jPanelsuperiorLayout = new javax.swing.GroupLayout(jPanelsuperior);
        jPanelsuperior.setLayout(jPanelsuperiorLayout);
        jPanelsuperiorLayout.setHorizontalGroup(
            jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsuperiorLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(222, 222, 222))
        );
        jPanelsuperiorLayout.setVerticalGroup(
            jPanelsuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsuperiorLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout espacioConfesLayout = new javax.swing.GroupLayout(espacioConfes);
        espacioConfes.setLayout(espacioConfesLayout);
        espacioConfesLayout.setHorizontalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelsuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        espacioConfesLayout.setVerticalGroup(
            espacioConfesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(espacioConfesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelsuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(espacioConfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel espacioConfes;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelsuperior;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListadoRevisores;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel txtCabecera;
    // End of variables declaration//GEN-END:variables
}
